name: Deploy to FTP

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: linux
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Deploy via FTP
        # pin to explicit version since "v4" tag isn't available
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp://194.36.184.209
          username: ${{ secrets.MFK_FTP_USER }}
          password: ${{ secrets.MFK_FTP_PASS }}
          local-dir: ./dist

